// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhP3l2Qg6qcH15xS55bFLViRno577vmnY',
    appId: '1:229608689606:web:45cc94236d4424ab2eacc7',
    messagingSenderId: '229608689606',
    projectId: 'eventflats',
    authDomain: 'eventflats.firebaseapp.com',
    databaseURL: 'https://eventflats-default-rtdb.firebaseio.com',
    storageBucket: 'eventflats.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ200hV1Wzkx5uhCJwjutbV0ENxYUcVN8',
    appId: '1:229608689606:android:b8eb95f56ca973cc2eacc7',
    messagingSenderId: '229608689606',
    projectId: 'eventflats',
    databaseURL: 'https://eventflats-default-rtdb.firebaseio.com',
    storageBucket: 'eventflats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnsu0cFrIAC_XbWYLGuUC_TwGpDY0GCfo',
    appId: '1:229608689606:ios:70b706b777a409f32eacc7',
    messagingSenderId: '229608689606',
    projectId: 'eventflats',
    databaseURL: 'https://eventflats-default-rtdb.firebaseio.com',
    storageBucket: 'eventflats.appspot.com',
    iosClientId: '229608689606-28ogunehl5bbt3f662perha5tl033o29.apps.googleusercontent.com',
    iosBundleId: 'uz.event.flat',
  );
}
